import numpy as np

shortnames = {
    "pos":"position",
    "u":"internalenergy",
    "rho":"density",
    "vol":"volume",
    "hsml":"smoothinglength",
    "vel":"velocity",
    "pres":"pressure",
    "acce":"acceleration",
    "pot":"potential",
    "grar":"densitygradient",
    "grav":"velocitygradient",
    "grap":"pressuregradient",
    "temp":"temperature"
}

rev_shortnames = dict((v,k) for k, v in shortnames.items())

hdf5toformat2 = {
'Coordinates': 'pos',
'Velocities': 'vel',
'ParticleIDs': 'id',
'Masses': 'mass',
'TracerField': 'trce',
'FluidQuantities': 'trfq',
'TracerID': 'trid',
'InternalEnergy': 'u',
'Density': 'rho',
'Volume': 'vol',
'Pressure': 'pres',
'ElectronAbundance': 'ne',
'NeutralHydrogenAbundance': 'nh',
'elect': 'elec',
'HI': 'hi',
'HII': 'hii',
'HM': 'hm',
'SmoothingLength': 'hsml',
'StarFormationRate': 'sfr',
'StellarFormationTime': 'age',
'FeedbackDone': 'fbdone',
'Metallicity': 'z',
'Potential': 'pot',
'Acceleration': 'acce',
'RateOfChangeOfEntropy': 'endt',
'DiagonalStressTensor': 'strd',
'OffDiagonalStressTensor': 'stro',
'BulkStressTensor': 'strb',
'ShearCoefficient': 'shco',
'TimeStep': 'tstp',
'MagneticField': 'bfld',
'DivBCleening': 'psi',
'SmoothedMagneticField': 'bfsm',
'RateOfChangeOfMagneticField': 'dbdt',
'DivergenceOfMagneticField': 'divb',
'ArtificialViscosity': 'abvc',
'ArtificialMagneticDissipatio': 'amdc',
'DissipationRate_DuDt': 'dudt',
'DivBcleaningFunctionPhi': 'phi',
'RotationB': 'rotb',
'SmoothedRotationB': 'srtb',
'EulerPotentialA': 'eula',
'EulerPotentialB': 'eulb',
'CoolingRate': 'coor',
'ConductionRate': 'conr',
'Denn': 'denn',
'PressureGradient': 'grap',
'DensityGradient': 'grar',
'VelocityGradient': 'grav',
'BfieldGradient': 'grab',
'BH_Mass': 'bhma',
'BH_Mdot': 'bhmd',
'BH_Hsml': 'bhhs',
'BH_HaloVvir': 'bhvv',
'BH_Pressure': 'bhpr',
'BH_U': 'bhu',
'BH_Density': 'bhro',
'BH_Mass_bubbles': 'bhmb',
'BH_Mass_ini': 'bhmi',
'BH_Progs': 'bhpr',
'BH_Mdot_Quasar': 'bhmq',
'BH_Mdot_Radio': 'bhmr',
'BH_CumMassGrowth_QM': 'bcmq',
'BH_CumEgyInjection_QM': 'bceq',
'BH_RadioLuminosity': 'bral',
'BH_XrayLuminosity': 'bxry',
'BH_CumMassGrowth_RM': 'bcmr',
'BH_CumEgyInjection_RM': 'bcer',
'BH_TimeStep': 'bhts',
'BH_BPressure': 'bhbp',
'MachNumber': 'mach',
'DtEnergy': 'dteg',
'Preshock_Density': 'psde',
'Preshock_Energy': 'psen',
'Preshock_XCR': 'psxc',
'DensityJump': 'djmp',
'EnergyJump': 'ejmp',
'CR_DtE': 'crde',
'2lpt-mass': 'soma',
'Center-of-Mass': 'cmce',
'Spin Center': 'lpos',
'Surface Area': 'area',
'Number of faces of cell': 'nfac',
'VertexVelocity': 'veve',
'Divergence of VertexVelocity': 'divv',
'Vorticity': 'vort',
'CellSpin': 'spin',
'Composition vector': 'comp',
'Nuclear Composition': 'xnuc',
'Passive Scalars': 'pass',
'Temperature': 'temp',
'Dust Temperature': 'dust',
'Photons': 'phot',
'PhotonDensity': 'phod',
'ChemicalAbundances': 'chem',
'TREECOL Column Density Map': 'coln',
'Gamma': 'gamm',
'HeatRate': 'heat',
'EscFrac': 'fesc',
'AllowRefinement': 'ref',
'GroupNr': 'grou',
'MaxFaceAngle': 'faca',
'HighResGasMass': 'hrgm',
'GFM_CoolingRate': 'gcol',
'GFM_StellarFormationTime': 'gage',
'GFM_InitialMass': 'gima',
'GFM_Metallicity': 'gz',
'GFM_Metals': 'gmet',
'GFM_DustAGB': 'gdag',
'GFM_DustSNII': 'gdii',
'GFM_DustMetallicity': 'gdz',
'GFM_StellarPhotometrics': 'gsph',
'GFM_AGNRadiation': 'agnr',
'ISM_ClumpPosition': 'cpos',
'ISM_ClumpDensity': 'cden',
'ISM_ClumpRadius': 'crad',
'VelocityDivergence': 'divv',
'VelocityCurl': 'rotv',
'CoolingHeatingEnergy': 'cohe',
'RefBHCounter': 'rebh',
'TurbulenceDissipation': 'vsdi',
'TurbulenceDriving': 'vsdr',
'SubfindDensity': 'sfde',
'SubfindHsml': 'sfhs',
'SubfindVelDisp': 'sfvd',
'MolecularHFrac': 'hmol',
'OpticalDepth': 'tau',
'CoolShutoffTime': 'cso',
'BlastRadius': 'brd',
'StarsHsml': 'ssml',
'SNIINumber': 'snii',
'FeedbackEnergy': 'ferg',
'MassReleased': 'mrel',
'MassEnriched': 'menr',
'BirthPos': 'birp',
'BirthVel': 'birv',
'TurbulentEnergy': 'utur',
'StromgrenRadius': 'strm',
'RadFeedTau': 'taud',
'RadFeed_NumNgb': 'rfnn',
'RadiationMomentumReleased': 'rade',
'RadVelocityKick': 'rfvk',
'EarlyCumulativeFeedback': 'efen',
'NormSphRadFeedback': 'rfns',
'RadCoolShutoffTime': 'rfcd',
'FeedbackEvents': 'fevt',
'GasRadCoolShutoffTime': 'rfcg',
'Eddington Tensor': 'eddt',
'Gamma': 'gamm',
'HI_fraction': 'hi',
'HII_fraction': 'hii',
'Source_Hsml': 'shsm',
'Source_GasDensity': 'srho',
'SIDM_Psum': 'sips',
'SIDM_NumNgb': 'sinn',
'SIDM_NumTotalScatter': 'sint',
'SIDM_Hsml': 'sihs',
'SIDM_Density': 'side',
'SIDM_VelDisp': 'sivd',
'RadiationPressureMoment': 'radp',
'HostHaloMass': 'hham',
'Star Index': 'sidx',
'RPSGalaxyMass': 'rps',
'CosmicRaySpecificEnergy': 'cren',
'Softenings': 'soft',
'GravityInteractions': 'gint',
'SFProbability': 'sfpr',
'RadiationFieldIntensity-OldStars': 'olds',
'RadiationFieldIntensity-NewStars': 'news'
    }

rev_hdf5toformat2 = dict((v,k) for k, v in hdf5toformat2.items())

default = [
    'id',
    'pos',
    'vel',
    'u',
    'mass'
    ]

present = {
    'id' : np.array([1,1,1,1,1,1]),
    'pos' : np.array([3,3,3,3,3,3]),
    'vel' : np.array([3,3,3,3,3,3]),
    'u'  : np.array([1,0,0,0,0,0]),           
    }

legacy_header_names = {
    'nparticles': 'NumPart_ThisFile',
    'masses': 'MassTable',
    'num_files': 'NumFilesPerSnapshot',
    'flag_sfr': 'Flag_Sfr',
    'flag_cooling': 'Flag_Cooling',
    'flag_feedback': 'Flag_Feedback',
    'flag_stellarage': 'Flag_StellarAge',
    'flag_metals': 'Flag_Metals',
    'ngroups': 'Ngroups_ThisFile',
    'ngroupsall': 'Ngroups_Total',
    'nids': 'Nids_ThisFile',
    'nidsall': 'Nids_Total',
    'nsubgroups': 'Nsubgroups_ThisFile',
    'nsubgroupsall': 'Nsubgroups_Total',
    'NumFiles': 'NumFilesPerSnapshot',
    'time': 'Time',
    'redshift': 'Redshift',
    'boxsize': 'BoxSize',
    'omega0': 'Omega0',
    'omegalambda': 'OmegaLambda',
    'hubbleparam': 'HubbleParam',
    'flag_doubleprecision': 'Flag_DoublePrecision'
    }

