#!python
import sys
import arepo

def usage():
    print("Usage: arepoinfo [OPTIONS] <filename>")
    print("")
    print("[OPTIONS] are:")
    print("  -p  --param   print parameters used (if available)")
    print("  -c  --config  print config options used (if available)")
    print("  -d  --dir     show which data fields are stored in this file")
    print("  -f  --format  specify file format if not auto detected")
    print("  -s  --subfind teat file as subfind output")
    exit()

if __name__ == "__main__":
    fname = ''
    param = False
    config = False
    onlyHeader = True
    format = None
    subfind = False
    
    if len(sys.argv) < 2:
        usage()
    
    it = iter(sys.argv[1:])
    for opt in it:
        if opt == "--param" or opt == "-p":
            param=True
            
        elif opt == "--config" or opt == "-c":
            config=True
            
        elif opt == "--dir" or opt == "-d":
            onlyHeader = False
            
        elif opt == "--format" or opt == "-f":
            format = int(it.next())
        
        elif opt == "--subfind" or opt == "-s":
            subfind = True
            
        elif opt == "--help" or opt == "-h":
            usage()
            
        elif not opt.startswith("-"):
            if fname == "":
                fname = opt
            else:
                usage()
                
        else:
            usage()
    
    if fname.find("fof_subhalo_tab") == -1 and subfind == False:
        sn = arepo.Snapshot(fname, format=format, combineFiles=False, onlyHeader=onlyHeader)
    else:
        sn = arepo.Subfind(fname, format=format, combineFiles=False, onlyHeader=onlyHeader)
    
    print(sn)
    
    if param and hasattr(sn, "parameters"):
        print(sn.parameters)
        
    if config and hasattr(sn, "config"):
        print(sn.config)